import type { Note } from "./types";

export const noteRegistry = [
  {
    id: "readme",
    title: "WestCose Labs README",
    summary: "The shortest useful orientation to the workstation.",
    preview: "Building software, designing systems, and exploring useful weird ideas.",
    updatedAt: "2026-08-06T17:30:00.000Z",
    tag: "README",
    tags: ["orientation", "system"],
    folderId: "project-notes",
    pinned: true,
    body: [
      "Building software. Designing systems. Making games. Exploring weird ideas.",
      "Every important destination is a real route. The operating-system layer adds personality without trapping the content.",
    ],
    desktopFileName: "WestCose Labs README.txt",
  },
  {
    id: "do-not-redesign",
    title: "Do not redesign this again",
    summary: "A preservation note written immediately before a careful redesign.",
    preview: "Keep the route model, the two OS shells, and the accessible fallback.",
    updatedAt: "2026-08-05T22:14:00.000Z",
    tag: "Process",
    tags: ["design", "guardrails"],
    folderId: "build-logs",
    body: [
      "Keep the route model, the two OS shells, the Dusk tokens, and the accessible fallback.",
      "Change the hierarchy where it feels generic. Keep the parts that already behave correctly.",
    ],
    desktopFileName: "Do not redesign this again.txt",
    titleMutation: {
      afterOpenCount: 5,
      alternateTitle: "Do not redesign this again (seriously)",
      discoveryId: "notes.title-mutated",
    },
  },
  {
    id: "features-nobody-asked-for",
    title: "Features nobody asked for",
    summary: "A small inventory of harmless side quests.",
    preview: "A Recycle Bin with emotional retention settings and a website lock screen.",
    updatedAt: "2026-08-04T09:20:00.000Z",
    tag: "System humor",
    tags: ["features", "side quests"],
    folderId: "questionable-ideas",
    body: [
      "A Recycle Bin with emotional retention settings.",
      "A lock screen for a website. A terminal that cannot damage anything. Window snapping for a portfolio.",
    ],
    desktopFileName: "Features nobody asked for.txt",
  },
  {
    id: "finish-first",
    title: "Things to finish before starting another SaaS",
    summary: "The list remains intentionally short and suspiciously reusable.",
    preview: "Finish the current project story. Verify the public links.",
    updatedAt: "2026-08-03T16:45:00.000Z",
    tag: "Process",
    tags: ["focus", "shipping"],
    folderId: "build-logs",
    body: [
      "Finish the current project story. Verify the public links. Export the approved screenshots.",
      "Only then is a new folder allowed to contain the word final.",
    ],
    desktopFileName: "Things to finish before starting another SaaS.txt",
  },
  {
    id: "names-at-214-am",
    title: "Names that sounded better at 2:14 AM",
    summary: "A humane quarantine zone for late-night product naming.",
    preview: "Cloud Forge, Thought Dock, and several names with an unnecessary X.",
    updatedAt: "2026-08-02T02:14:00.000Z",
    tag: "Ideas",
    tags: ["naming", "late night"],
    folderId: "questionable-ideas",
    body: [
      "Cloud Forge. Thought Dock. Localhost but with an unnecessary X.",
      "No domain names were purchased while writing this note. That counts as progress.",
    ],
    desktopFileName: "Names that sounded better at 2.14 AM.txt",
  },
  {
    id: "client-phrases",
    title: "Client phrases translated into English",
    summary: "A small glossary for keeping product conversations concrete.",
    preview: "Make it pop means clarify the priority, contrast, and desired action.",
    updatedAt: "2026-08-01T19:05:00.000Z",
    tag: "Translation",
    tags: ["clients", "communication"],
    folderId: "client-translations",
    body: [
      "Make it pop: clarify the priority, contrast, and action the interface should support.",
      "Can we make it more premium: identify the audience, proof, and level of restraint before changing the surface.",
      "Quick change: inspect the surrounding system before estimating it.",
    ],
    desktopFileName: "Client phrases translated into English.txt",
  },
  {
    id: "final-final-v8",
    title: "Final_FINAL_v8",
    summary: "The filename has reached a stable and legally binding conclusion.",
    preview: "Renaming is unavailable because this version is already final.",
    updatedAt: "2026-07-31T23:58:00.000Z",
    tag: "Build log",
    tags: ["final", "probably"],
    folderId: "build-logs",
    body: [
      "This is the final version.",
      "The previous seven final versions remain available for historical accuracy and emotional support.",
    ],
    desktopFileName: "Final_FINAL_v8.txt",
  },
  {
    id: "games-after-current-game",
    title: "Games to build after finishing the current game",
    summary: "A parking lot that protects the project currently in progress.",
    preview: "One tiny tactics game, one impossible simulator, and no new engine rewrite.",
    updatedAt: "2026-07-30T11:40:00.000Z",
    tag: "Ideas",
    tags: ["games", "later"],
    attachmentCount: 2,
    folderId: "questionable-ideas",
    body: [
      "One tiny tactics game. One impossible simulator. One project with a scope that fits on an index card.",
      "Finish the current game before choosing an engine, naming a repository, or drawing a skill tree.",
    ],
    desktopFileName: "Games to build after finishing the current game.txt",
  },
  {
    id: "passwords-not-passwords",
    title: "Passwords that are definitely not passwords",
    summary: "A hidden note containing no credentials and one useful reminder.",
    preview: "There are no passwords here. Use a password manager anyway.",
    updatedAt: "2026-07-29T08:10:00.000Z",
    tag: "System humor",
    tags: ["hidden", "security"],
    folderId: "questionable-ideas",
    hidden: true,
    discoveryId: "notes.hidden-note-opened",
    body: [
      "There are no passwords here.",
      "Use a password manager, enable multi-factor authentication, and never store credentials in a portfolio note.",
    ],
    desktopFileName: "Passwords that are definitely not passwords.txt",
  },
] as const satisfies readonly Note[];

export type RegisteredNote = (typeof noteRegistry)[number];

export function getNote(id: string): RegisteredNote | undefined {
  return noteRegistry.find((note) => note.id === id);
}
